openapi: 3.1.0
info:
  title: [Nombre de la API]
  description: [Resumen funcional del contrato de API]
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Servidor de desarrollo
paths:
  /[endpoint]:
    get:
      summary: [Breve descripción]
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/[Objeto]'
components:
  schemas:
    [Objeto]:
      type: object
      properties:
        id:
          type: string
          format: uuid
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
